services:

  dev: 
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      VITE_API_BASE_URL:  ${VITE_API_BASE_URL}
      PORT: 5174
    ports:
      - 5174:5174
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./index.html:/app/index.html

  release:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 80
      VITE_API_BASE_URL:  ${VITE_API_BASE_URL}
    ports:
      - 80:80